@startuml

class AdministrationAgreement {
  - String uuid (?..?)
  - String employerUuid (?..?)
  - String administrationOfficeUuid (?..?)
  - LocalDate startDate (?..?)
  - LocalDate endDate (?..?)
  - List<String> annotations (?..?)
}

@enduml
